### ISSUE TITLE
Human readable output

### ISSUE THREAD

**Issue by pksjce** [mozilla-rpweb/webpack-chain#11]
I tried out the api and tried to create a minimal configuration with only entrypoint ,outputPath and outputFilename.
I get output something like
`
{"output":{"path":"dist","filename":"bundle.js"},"resolve":{"modules":[],"extensions":[]},"resolveLoader":{"modules":[]},"plugins":[],"entry":{"index":['index.js']}}
`

Wouldn't it be better to prune out the empty configs of `resolve`, `resolveLoader` and `plugins`?

**Comment by eliperelman** [comment]
Yes, should be easy enough, right now we remove undefined entries from objects, just need to do for arrays as well.

**Comment by eliperelman** [comment]
Fixed in b428e55a671a033c133ba2e225796845307dee12. Published to npm at v1.4.3.
