### ISSUE TITLE
module.rule(...).loader(...).use is not a function

### ISSUE THREAD

**Issue by sean-clayton** [mozilla-rpweb/webpack-chain#5]
I'm considering using Neutrino (which uses this package) and I'm trying to add ExtractTextPlugin (https://github.com/webpack-contrib/extract-text-webpack-plugin) to my Neutrino project.

The extract-text-webpack-plugin docs use this example:

```js
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
  ]
}
```

So, I assumed this would be the equivalent for webpack-chain (this is a custom preset being called in my package.json):

```js
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = ({ config }) => {
  config.module
    .rule("css")
    .use(ExtractTextPlugin.extract, {
      fallback: "style-loader",
      use: "css-loader"
    });
  config.plugin("extract-css").use(ExtractTextPlugin, "styles.css");
};
```

But I get the following error:

```sh
config.module.rule(...).loader(...).use is not a function
```

Am I doing anything wrong here?

**Comment by sean-clayton** [comment]
@eliperelman Unfortunately not :( I don't think it's an issue with webpack-chain at this point, though, so I'm going to go ahead and close the ticket—thank you for the help, though 😄

**Comment by eliperelman** [comment]
@sean-clayton ah ok. Please let me know if you find out what the issue was, and if you think there is something actionable we can do here. Thanks!

**Comment by sean-clayton** [comment]
@eliperelman I did a little more messing around and I got a build to successfully output a CSS file via the extract plugin, but it looks like css-loader doesn't take effect (I have `minimize` set to true, but the extracted CSS is not minimized).

I've created a repo here: https://github.com/sean-clayton/neutrino-test

The steps to reproduce are:

- Install deps: `yarn install`
- Run build: `yarn build`

Again, I'm _not sure_ this is a problem with webpack-chain.
